# --- 基本信息 -------------------------------------------------------------
site_name: Shumeng Zhang
site_url: https://realsumen.github.io
site_author: Shumeng Zhang
site_description: Notes & Resume

# --- 导航 (只列出现有的两篇文件) -----------------------------------------
# docs_dir 设为 "."，所以路径直接写你仓库里的相对位置
docs_dir: "."

nav:
  - Notes:
      - Empirical Market Structure: _notes/empirical-market-strucuture.md
  - Resume: _resume/index.md

# --- 主题 ------------------------------------------------------------------
theme:
  name: material
  language: zh
  features:
    - navigation.indexes      # 点击 Tab 默认打开 index.md（可选，留着也行）
    - navigation.top          # 上滑出现“返回顶部”按钮
    - search.highlight
    - search.suggest

# --- 插件 ------------------------------------------------------------------
plugins:
  - search:
      lang: [zh, en]

# --- Markdown 扩展 (择一两个常用的即可) -----------------------------------
markdown_extensions:
  - toc:
      permalink: true
  - admonition
