title: Shumeng Zhang
logo: asset/image/selfie.jpg
show_downloads: false
theme: jekyll-theme-minimal

collections:
  notes:
    output: true
    permalink: /notes/:title/
  resume:
    output: true
    permalink: /resume/

# （可选）导航栏
nav:
  - name: Notes
    link: /notes/
  - name: Resume
    link: /resume/

