site_name: Shumeng Zhang
site_url: https://realsumen.github.io
site_author: Shumeng Zhang
site_description: Notes & Resume

docs_dir: "docs"

nav:
  - Home: index.md
  - Book Notes:
      - Empirical Market Structure: _notes/empirical-market-strucuture.md
      - Market Microstructure Theory: _notes/market-microstructure-theory.md
      - Probability Theory and Examples: _notes/probability-theory-and-examples.md
  - About ME: _resume/index.md

theme:
  name: material
  language: zh
  features:
    - navigation.indexes      # 点击 Tab 默认打开 index.md（可选，留着也行）
    - navigation.top          # 上滑出现“返回顶部”按钮
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to Night Mode
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode

plugins:
  - search:
      lang: [zh, en]

markdown_extensions:
  - toc:
      permalink: true
  - admonition
